### ISSUE TITLE
Issue using @ExpectedDataSet without @DataSet

### ISSUE THREAD

**Issue by internetstaff** [database-rider/database-rider#136] opened 2019-05-30 22:15 UTC
I'm using Spring Boot, Jooq, HikariCP, and Rider-Spring. For the most part, this combination works fine.

I have one test in one class that is marked @Test, @ExpectedDataSet and does nothing but insert a couple of records via JooQ, then verify their existence.

The class is annotated:

```
@RunWith(SpringRunner.class)
@JooqTest
@DBRider
```

The test works when run alone or only that class is run.

When I run it with multiple test classes, this one test in the one class fails with:

junit.framework.ComparisonFailure: row count (table=mytable) expected:<[2]> but was:<[0]>

The transaction is not only not visible, but isn't rolled back either - the two records will be left in the database. It seems like some kind of Spring related connect / datasource / pool related issue that I've been unable to track down.

Today I realized that, when I add a @DataSet that has no relation to the actual test, this all works fine.  I'm glad I found a work around, but it seems like there's still something wrong.

Any ideas?

Thanks for you work on this!

**Comment by rmpestano** [comment] 2019-05-30 23:03
Hi @internetstaff,

is your test marked as `@Transactional` like [this example](https://github.com/database-rider/database-rider/blob/master/rider-spring/src/test/java/com/github/database/rider/spring/expected/ExpectedDataSetIT.java#L43)? 

Any hints @njuro? 

Would be nice if we could reproduce in [rider-spring tests](https://github.com/database-rider/database-rider/blob/master/rider-spring/src/test/java/com/github/database/rider/spring/expected/ExpectedDataSetIT).

Thanks for reporting

**Comment by internetstaff** [comment] 2019-05-30 23:08
Unfortunately, `@Transactional` doesn't make any difference.

**Comment by rmpestano** [comment] 2019-05-30 23:17
Declaring `@DataSet(cleanBefore=true)` at class level also solves it ?

**Comment by jenskreidler** [comment] 2019-05-31 07:42
Hi,
depending on your setup it could solve your issue using @Commit (spring-test) or @DirtiesContext(...) (also from spring-test).
Greetings

Am 31. Mai 2019 00:15:05 MESZ schrieb Possibly Cott <notifications@github.com>:
>I'm using Spring Boot, Jooq, HikariCP, and Rider-Spring. For the most
>part, this combination works fine.
>
>I have one test in one class that is marked @Test, @ExpectedDataSet and
>does nothing but insert a couple of records via JooQ, then verify their
>existence.
>
>The class is annotated:
>
>```
>@RunWith(SpringRunner.class)
>@JooqTest
>@DBRider
>```
>
>The test works when run alone or only that class is run.
>
>When I run it with multiple test classes, this one test in the one
>class fails with:
>
>junit.framework.ComparisonFailure: row count (table=mytable)
>expected:<[2]> but was:<[0]>
>
>The transaction is not only not visible, but isn't rolled back either -
>the two records will be left in the database. It seems like some kind
>of Spring related connect / datasource / pool related issue that I've
>been unable to track down.
>
>Today I realized that, when I add a @DataSet that has no relation to
>the actual test, this all works fine.  I'm glad I found a work around,
>but it seems like there's still something wrong.
>
>Any ideas?
>
>Thanks for you work on this!
>
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/database-rider/database-rider/issues/136

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by internetstaff** [comment] 2019-06-11 15:41
Sorry for the delay - hard to get time in on this. I've traced this farther - the @DataSet was a red herring: I had randomly tried a @DataSet that matched our @ExpectedDataSet, so I was effectively validatingmy own test dataset. :man_facepalming:  :rofl: 

`@DataSet(cleanBefore=true)` doesn't help.

Various combinations of `@DirtiesContext` seem to either do nothing or produces AnnotationConfigApplicationContext "has been closed already". :)

I've narrowed it down to two specific tests running in this order:

1. A test against an application class that encapsulates a specific DAO class.

2. A test against the specific DAO class directly. 

When run together, in that order, the DAO class fails @ExpectedDataSet. When run separately, it works fine.

I've traced this and it _appears_ that the two tests use different DAOs, different DataSources, different Hikari Pools, and different contexts. This seems expected.

However, I see that DBRider's DataSetExecutorImpl in the second test is still referencing "HikariPool-1" whereas the test is running with "HikariPool-2".

I'm not sure which is unexpected: our tests having different HikariPools or DBRider using one from the earlier Context. :)

Our application test is annotated:

```
@RunWith(SpringRunner.class)
@SpringBootTest(classes = {SomeApplication.class, SomeConfig.class})
@ActiveProfiles("test")
@DBRider
```

Our DAO test is annotated:

```
@RunWith(SpringRunner.class)
@JooqTest
@ContextConfiguration(classes = {SomeDAO.class})
@ActiveProfiles("test")
@DBRider

```
If we use @SpringBootTest on both classes, both tests use HikariPool-1 and the test works.

While it's nice to have a fix, we'd prefer to be using a @JooqTest slice.I'd definitely like to understand what we're doing wrong - especially if there's any opportunities for improvement if only documentation for people like me! :)

Thanks again for your input on this!

**Comment by rmpestano** [comment] 2019-06-11 16:25
Hi @internetstaff, thanks for the detailed answer.

Following is how the jdbc connection is handled in dbrider:
 
Each DataSetExecutor is responsible for one connection, see [instance method here](https://github.com/database-rider/database-rider/blob/656eecb92aa660ea6f164e9c8e6899d5f3a19b5b/rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java#L90). After the executor is instantiated it will always use the same connection.

Now looking at Spring module it instantiates the [executor here]( https://github.com/database-rider/database-rider/blob/656eecb92aa660ea6f164e9c8e6899d5f3a19b5b/rider-spring/src/main/java/com/github/database/rider/spring/SpringRiderTestContext.java#L23) without specifying the executor ID so the [default one will be used](https://github.com/database-rider/database-rider/blob/656eecb92aa660ea6f164e9c8e6899d5f3a19b5b/rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java#L87), maybe we should specify the executor id based on the test class name may help for this case but as I'm not a Spring expert I'll let you guys find the best solution.

I also noticed the SpringRiderTestContext is trying to [clear the datasource here](https://github.com/database-rider/database-rider/blob/656eecb92aa660ea6f164e9c8e6899d5f3a19b5b/rider-spring/src/main/java/com/github/database/rider/spring/SpringRiderTestContext.java#L24) but it looks like it has no effect because the [connection holder is not cleared ](https://github.com/database-rider/database-rider/blob/656eecb92aa660ea6f164e9c8e6899d5f3a19b5b/rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java#L911).

Also note that `@DataSet` annotation has a `executor` parameter maybe the SpringRiderTestContext could use it to decide which executor to use. 

@artemy-osipov, @njuro any ideas? 

Thank you guys

**Comment by rmpestano** [comment] 2019-06-11 17:05
Also, disabling cachedConnections in DBUnit config may help, remembered it after looking at executor code [here](https://github.com/database-rider/database-rider/blob/656eecb92aa660ea6f164e9c8e6899d5f3a19b5b/rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java#L97).

Ex:

```
@DBUnit(cacheConnection = false)
@RunWith(SpringRunner.class)
@SpringBootTest(classes = {SomeApplication.class, SomeConfig.class})
@ActiveProfiles("test")
@DBRider
```

**Closed** 2020-12-16 21:59 UTC

**Comment by Aganiyaz** [comment] 2024-09-26 13:41
@Transactional annotation helped me, the error was in expected table, expected = 0, exists = 1.
