### ISSUE TITLE
invalid schema name

### ISSUE THREAD

**Issue by hugol1ma** [database-rider/database-rider#49] opened 2017-10-25 14:08 UTC
Hi,

i get error when init my tests

For production i use SQL Server and i have schema named: dbo

My Class User:
`@Entity
@Table(name="USER",schema="dbo",catalog = "MYCATALOG")
public class User {
...
} `

when run test i got error: invalid schema name: DBO
and also: user lacks privilege or object not found: USER

if remove schema="dbo" its works perfectly.
What could be wrong?

Thanks

**Comment by rmpestano** [comment] 2017-10-25 14:46
Hi, Are you defining the schema on the dataset? See Flyway tests for example: https://github.com/database-rider/database-rider/blob/master/rider-examples/jOOQ-DBUnit-flyway-example/src/test/resources/datasets/authors.yml#L1

I hope it helps

**Comment by hugol1ma** [comment] 2017-10-26 14:06
Yes, i write with `dbo.user:`, tried too  `mycatalog.dbo.user:`, 
`user:` ... All attempts had no effect, all with the same error
everything works only if I remove the schema parameter from the annotation `@Table`

I look now, you example doesn't contains file persistence.xml... On my project always had. 
Can this create some conflict?

My persistence is similar to this: [https://github.com/database-rider/database-rider/blob/master/rider-examples/jpa-productivity-boosters/src/test/resources/META-INF/persistence.xml](url)

**Comment by rmpestano** [comment] 2017-10-26 19:32
Hi @hugol1ma,

I'm getting the same error and could not figure out. I've added a [test here](https://github.com/database-rider/database-rider/blob/master/rider-junit5/src/test/java/com/github/database/rider/junit5/DBUnitJUnit5ChemaIt.java) if someone wants to play with with. 

It basically uses hsqldb PUBLIC schema and also configured [JPA entities](https://github.com/database-rider/database-rider/tree/master/rider-junit5/src/test/java/com/github/database/rider/junit5/model/schema) with the same schema and set it as default schema in [persistence.xml](https://github.com/database-rider/database-rider/blob/master/rider-junit5/src/test/resources/META-INF/persistence.xml#L40). Here's the error:

```
java.lang.RuntimeException: Could not create dataset for test method shouldUpdateUser due to following error Could not initialize dataset: usersWithTweetAndSchema.yml
Caused by: com.github.database.rider.core.exception.DataBaseSeedingException: Could not initialize dataset: usersWithTweetAndSchema.yml
	at com.github.database.rider.core.dataset.DataSetExecutorImpl.createDataSet(DataSetExecutorImpl.java:160)
	at com.github.database.rider.junit5.DBUnitExtension.beforeTestExecution(DBUnitExtension.java:108)
	... 46 more
Caused by: org.dbunit.dataset.NoSuchTableException: PUBLIC.TWEET
	at org.dbunit.database.DatabaseDataSet.getTableMetaData(DatabaseDataSet.java:305)
	at org.dbunit.operation.DeleteAllOperation.execute(DeleteAllOperation.java:109)
	at org.dbunit.operation.CompositeOperation.execute(CompositeOperation.java:79)
	at com.github.database.rider.core.dataset.DataSetExecutorImpl.createDataSet(DataSetExecutorImpl.java:156)
	... 47 more

```

**Comment by cherniag** [comment] 2019-01-14 16:43
If I use h2 database, cleanBefore and cleanAfter don't work because schema is ignored.
In the code of method:
com.github.database.rider.core.dataset.DataSetExecutorImpl#resolveSchema(java.sql.ResultSet)
`schemaName = result.getString("TABLE_SCHEMA");`
but h2 uses alias TABLE_SCHEM:
```
 String tableSelect = "SELECT "
                    + "TABLE_CATALOG TABLE_CAT, "
                    + "TABLE_SCHEMA TABLE_SCHEM, "
                    + "TABLE_NAME, "
                    + "TABLE_TYPE, "
                    + "REMARKS, "
                    + "TYPE_NAME TYPE_CAT, "
                    + "TYPE_NAME TYPE_SCHEM, "
                    + "TYPE_NAME, "
                    + "TYPE_NAME SELF_REFERENCING_COL_NAME, "
                    + "TYPE_NAME REF_GENERATION, "
                    + "SQL "
                    + "FROM INFORMATION_SCHEMA.TABLES "
                    + "WHERE TABLE_CATALOG LIKE ? ESCAPE ? "
                    + "AND TABLE_SCHEMA LIKE ? ESCAPE ? "
                    + "AND TABLE_NAME LIKE ? ESCAPE ? "
                    + "AND (" + tableType + ") ";
```
So schema inside DataSetExecutorImpl will be always null

**Comment by rmpestano** [comment] 2019-01-14 16:58
Interesting, we may have to check driver type (like we do in [disable/enable constraints](https://github.com/database-rider/database-rider/blob/410ec87f83d7a3cf500dfa12c447896c0be764af/rider-core/src/main/java/com/github/database/rider/core/dataset/DataSetExecutorImpl.java#L325)) before resolving schema name.

Anyone want to contribute? A passing test case using H2 and cleanBefore/cleanAfter (like [this one](https://github.com/database-rider/database-rider/blob/master/rider-core/src/test/java/com/github/database/rider/core/CleanBeforeAfterIt.java#L20)) would be great!

**Comment by juliocesarsantos1020** [comment] 2019-12-12 18:07
Hello guys, I'm having this problem too.
Caused by: org.dbunit.dataset.NoSuchTableException: The table 'Table' does not exist in schema '', is there any solutions ?

**Comment by rmpestano** [comment] 2020-04-15 08:17
Guys, you can configure schema using [DBUnit configuration](https://github.com/database-rider/database-rider#332-dbunit-configuration), please try with latest version and let me know if you still face the issue.

Also the issue I [mentioned here](https://github.com/database-rider/database-rider/issues/49#issuecomment-339776034) does no longer exists so I hope yours also don't. 

Please reopen the issue with a reproducer in case it doesn't work for you.

**Closed by rmpestano** 2020-04-15 08:17 UTC
Labels: bug
