### ISSUE TITLE
UUID in PostgreSQL order

### ISSUE THREAD

**Issue by gitterhh** [database-rider/database-rider#213] opened 2020-06-23 15:48 UTC
I use same dataset provider for `@DataSet` and `@ExpectedDataSet`
```
@Test
@DataSet(provider = ProductsDataSetProvider.class)
@ExpectedDataSet(provider = ProductsDataSetProvider.class)
public void test() {
    // ...
}

public class ProductsDataSetProvider implements DataSetProvider {

        @Override
        public IDataSet provide() {
            return new DataSetBuilder()
                    .table("products")
                    .columns("id")
                    .values("a2b1d64d-5070-4852-8968-d54d2b0a0c71")
                    .values("4d28c213-5969-4143-910d-db736a93fac5")
                    .build();
        }
    }
```
And I am getting an error
```
junit.framework.ComparisonFailure: value (table=products, row=0, col=id) expected:<[a2b1d64d-5070-4852-8968-d54d2b0a0c71]> but was:<[4d28c213-5969-4143-910d-db736a93fac5]>
```
If I change the order everything is good.
Is it possible somehow to indicate to not sort the id order?

**Comment by rmpestano** [comment] 2020-06-24 08:49
Hi, can you try to use `orderBy` on expected dataset?

```
@ExpectedDataSet(provider = ProductsDataSetProvider.class, orderBy = "id")

```

**Comment by gitterhh** [comment] 2020-06-24 12:59
It shows that "4d28c213-5969-4143-910d-db736a93fac5" is on first position, but in provider it is on second position.
I do not need to order the data set, I expect the order to be like in the provider.

**Comment by rmpestano** [comment] 2020-07-02 07:08
So I create a small reproducer:

```
    @Test
    @DataSet(provider = TweetDataSetProvider.class)
    @ExpectedDataSet(provider = TweetDataSetProvider.class)
    public void test() {

    }

    public static class TweetDataSetProvider implements DataSetProvider {

        @Override
        public IDataSet provide()  {
            DataSetBuilder builder = new DataSetBuilder();
            builder.table("TWEET")
                    .row()
                    .column("ID", "a2b1d64d").column("CONTENT", "dbrider rules!")
                    .column("DATE", "[DAY,NOW]")
                    .row()
                    .column("ID", "4d28c213").column("CONTENT", "dbrider rules!")
                    .column("DATE", "[DAY,NOW]");
            return builder.build();
        }
    }
```

and the problems seems to be with the way DBUnit creates datasets from current  db connection, see the prints where `expected` is the dataset DBRider creates using the dataset provider and `current` is the one created by DBUnit:

current: <img width="1042" alt="Screenshot 2020-07-02 at 09 03 06" src="https://user-images.githubusercontent.com/1592273/86327048-e4295980-bc42-11ea-9f46-5a60d3196845.png">

expected: 
<img width="1082" alt="Screenshot 2020-07-02 at 08 59 10 2" src="https://user-images.githubusercontent.com/1592273/86327123-058a4580-bc43-11ea-9636-e4eaa9fa352b.png">

I don't think there is much we can do on DBRider side but I'll let this issue opened.

Note that both `@ExpectedDataSet(provider = TweetDataSetProvider.class, compareOperation = CompareOperation.CONTAINS)` OR `@ExpectedDataSet(provider = TweetDataSetProvider.class, orderBy = "id")`

Works for this case.

**Comment by rmpestano** [comment] 2020-07-02 08:19
Also look on how we seed the database, it also preserves the order of declaration in dataset provider:

<img width="1072" alt="Screenshot 2020-07-02 at 10 17 01" src="https://user-images.githubusercontent.com/1592273/86334389-6f0f5180-bc4d-11ea-831a-c04a90d9aa4c.png">

<img width="1140" alt="Screenshot 2020-07-02 at 10 17 39" src="https://user-images.githubusercontent.com/1592273/86334371-67e84380-bc4d-11ea-9d2e-a9ed8007dab9.png">

**Comment by rmpestano** [comment] 2020-07-02 08:22
Thinking better, as we create **current** dataset from db connection, there is no way to dbunit know the order of the declaration in dataset. 

So if you want to guarantee order you need to use `orderBy` or `compareOperation = CompareOperation.CONTAINS`. 

I'm closing the issue, thanks for your feedback.

**Closed by rmpestano** 2020-07-02 08:22 UTC
